config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  get 'users/index'
  get 'users/show'
  get 'users/new'
  get 'users/create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root to: 'tasks#index'
    resources :tasks
    
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
    
    get 'signup', to: 'users#new'
    resources :users, only: [:index, :show, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :user
    validates :content, presence: true, length: {maximum: 255}
    validates :status, presence: true, length: {maximum: 10}
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
                    
  has_secure_password
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
  include SessionsHelper
  
  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
  
  def counts(user)
    @count_tasks = user.tasks.count
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to("/")
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
    private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:destroy, :edit, :update, :show]
  
  def index
     @task = current_user.tasks.build  # form_with 用
     @tasks = current_user.tasks.order(id: :desc).page(params[:page])
  end

  def show
      @task = Task.find(params[:id])
  end

  def new
      @task = Task.new
  end

  def create
      @task = current_user.tasks.build(task_params)
      
      if @task.save
          flash[:success] = "タスクが正常に登録されました"
          redirect_to @task
      else
          flash.now[:danger] = "タスクを登録できませんでした"
          render :new
      end
  end

  def edit
      
  end

  def update
      if @task.update(task_params)
          flash[:success] = "タスクが正常に更新されました"
          redirect_to(@task)
      else
          flash[:danger] = "タスクは更新されませんでした"
          render(:edit)
      end
  end

  def destroy
      @task.destroy
      flash[:success] = "タスクは正常に削除されました"
      redirect_back(fallback_location: root_path)
  end
  
  
  private
  
    # Strong Parameter
  def task_params
    params.require(:task).permit(:content, :status)
  end
  
  def correct_user
    @task = current_user.tasks.find_by(id: params[:id])
    unless @task
      redirect_to root_url
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show]
  
  def index
    @users = User.order(id: :asc).page(params[:page]).per(25)
  end

  def show
    @user = User.find(params[:id])
    @tasks = @user.tasks.order(id: :desc).page(params[:page])
    counts(@user)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_tasks.html.erb
<% flash.each do |task_type, task| %>
  <div><%= task %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render("layouts/flash_tasks") %>
    
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |f| %>

  <% if task.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


    <%= f.label :status, "進捗率" %>
    <%= f.text_field :status %>

    <%= f.label :content, "タスク" %>
    <%= f.text_field :content %>
    
    <%= f.submit "登録" %>
<% end %>

app/views/tasks/_tasks.html.erb
<ul class="list-unstyled">
  <% tasks.each do |task| %>
    <li class="media mb-3">
      <div class="media-body">
        <div>
          作成者: <%= link_to task.user.name, user_path(task.user) %>, <span class="text-muted">進捗率: <%= task.status %></span>
        </div>
        <div>
          <p><%= task.content %></p>
        </div>
        <div>
          <% if current_user.id == task.user.id %>
            <%= link_to "Delete", task, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger btn-sm' %>
            <%= link_to 'Edit', edit_task_path(task) %>
          <% end %>
        </div>
      </div>
    </li>
  <% end %>
  <%= paginate tasks %>
</ul>

app/views/tasks/edit.html.erb
<h2>id: <%= @task.id %>のタスク編集ページ</h2>

<%= render 'form', task: @task %>

<%= link_to("タスク一覧に戻る","/tasks") %>

app/views/tasks/index.html.erb
<% if logged_in? %>
  <p>ログイン完了ユーザ: <%= current_user.name %></p>
    <%= link_to("Task Addition", new_task_path) %>
    <%= link_to 'Logout', logout_path, method: :delete %>

<% else %>
  <div class="center jumbotron">
    <div class="text-center">
      <h1>My Task List</h1>
      <%= link_to 'Sign up', signup_path, class: 'btn btn-lg btn-primary' %>
      <%= link_to 'Login', login_path, class: 'btn btn-lg btn-primary' %>
    </div>
  </div>
<% end %>

<h1>タスク一覧</h1>

<%= render 'tasks/tasks', tasks: @tasks %>

<%= paginate @tasks %>

app/views/tasks/new.html.erb
<h1>タスク新規作成ページ</h1>

<%= render 'form', task: @task %>

<%= link_to("タスク一覧に戻る","/tasks") %>

app/views/tasks/show.html.erb
<h1>id: <%= @task.id %>のタスク詳細ページ</h1>

<p>進捗率: <%= @task.status %></p>
<p>タスク内容: <%= @task.content %></p>

<%= link_to("タスク一覧に戻る", tasks_path) %>
<%= link_to("このタスクを編集する", edit_task_path(@task)) %>
<%= link_to("このタスクを削除する", @task, method: :delete, data: { confirm: '本当に削除してよろしいですか？' }) %>

app/views/users/_users.html.erb
<% if users.any? %>
  <ul class="list-unstyled">
    <% users.each do |user| %>
      <li class="media">
        <img class="mr-2 rounded" src="<%= gravatar_url(user, { size: 50 }) %>" alt="">
        <div class="media-body">
          <div>
            <%= user.name %>
          </div>
          <div>
            <p><%= link_to 'View profile', user_path(user) %></p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%= paginate users %>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<h1>User List</h1>
<%= render 'users', users: @users %>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user, local: true) do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit 'Sign up', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
    <% if current_user == @user %>
    <%= link_to("Task Addition", new_task_path) %>
    <% end %>
    <%= link_to("Task List", tasks_path) %>
    <%= link_to 'Logout', logout_path, method: :delete %>
  <aside class="col-sm-6">
    <div class="card">
      <div class="card-header">
        <h2 class="card-title">User Name: <%= @user.name %></h2>
      </div>
      <div class="card-body">
        <img class="rounded img-fluid" src="<%= gravatar_url(@user, { size: 400 }) %>" alt="">
      </div>
    </div>
  </aside>
  <div class="col-sm-6">
    <h2>Number of Tasks: <%= @count_tasks %></h2>
    <%= render 'tasks/tasks', tasks: @tasks %>
  </div>
</div>